### ISSUE TITLE
Handle GET, PATCH and DELETE requests

### ISSUE THREAD

**Issue by mrmuhammadali** [fusionjs/fusion-plugin-rpc-redux-react#153]
### Type of issue
Feature

### Description
Handle other requests types as well, i.e. GET, PATCH and DELETE.

**Comment by ganemone** [comment]
The goal of the web-rpc abstraction is to remove the need to think about HTTP/REST semantics. In theory, the web-rpc interface is agnostic of the transport mechanism. I don't think we will be adding support for http specific customizations.

**Comment by mrmuhammadali** [comment]
So how external services will communicate with our app? Let's say I have registered a webhook on some external service.
