### ISSUE TITLE
React-Redux 6.0.0 package breaks dispatch

### ISSUE THREAD

**Issue by chiwoojo** [fusionjs/fusion-plugin-rpc-redux-react#166]
### Type of issue

bug

### Description

Dispatch gets broken. Maybe something to do with this.context?..

![image pasted at 2019-1-8 15-13](https://user-images.githubusercontent.com/13400593/50865599-398cef00-135b-11e9-89ae-3f809675c866.png)

### Current behavior

store.dispatch does not exist.

### Expected behavior

store.dispatch should exist.

### Steps to reproduce

1. install react-redux 6.0.0
2. run rpc calls 

### Your environment

* fusion-plugin-rpc-redux-react version:
2.0.2
* Node.js version (`node --version`):
8.11.3
* npm version (`npm --version`):
5.6.0

* Operating System:
mac os x 10.14.2

**Comment by chiwoojo** [comment]
going down to v5.x.x fixed this issue.

**Comment by kahwee** [comment]
I can confirm this as well. Can we set `react-redux` as a peerDependency and set it to `^v5.0.0` until this gets resolved?

**Comment by VladimirMilenko** [comment]
Issue is caused due to `react-redux` using `React.createContext`.
So, workaround is to use v5 unless providers will be implemented using `createContext`

**Comment by markerikson** [comment]
Hi, I'm a Redux maintainer.

The real solution here is to update the library to correctly read the store out of the `ReactReduxContext` instance for compatibility with v6, and release an updated version.

See our docs page here: [React-Redux: Accessing the Store](https://react-redux.js.org/using-react-redux/accessing-store).

**Comment by zebralight** [comment]
Does this issue being closed mean that React-Redux >= 6 is good to use with this plugin?

**Comment by markerikson** [comment]
No, this library is currently only compatible with <= v5, and breaks with >= v6.
